### ISSUE TITLE
License

### ISSUE THREAD

**Issue by IeuanGol** [idzan/dynamic-landing-page#1]
Are we allowed to use this repository?

If so could you please add a license.

Thank you. :)

https://choosealicense.com/

**Comment by idzanhr** [comment]
Hello :)

Yes, you are allowed to use this repository for your personal usage or for improvements which you can get to Pull 👍 

Please give me few moments to apply GNU GPLv3 License to this repo 😃 

Thanks and enjoy in work @IeuanGol

**Comment by IeuanGol** [comment]
Thank you so much! 😄
